# Generated by Django 5.2.4 on 2025-07-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_phone_number_alter_article_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post',
            new_name='content',
        ),
    ]
